#ifndef MQTT_VSOME_IP_CONF_HPP_
#define MQTT_VSOME_IP_CONF_HPP_

#define MQTT_SERVICE_ID 0x1239
#define MQTT_INSTANCE_ID 0x5670
#define MQTT_EVENTGROUP_ID 0x9C90

#define GNSS_REQUEST_SERVICE_ID 0x1242
#define GNSS_REQUEST_INSTANCE_ID 0x5675
#define GNSS_REQUEST_EVENT_ID 0x9C47
#define GNSS_REQUEST_EVENTGROUP_ID 0x9C40


#define BACKEND_REQUEST_SERVER_SERVICE_ID 0x1234
#define BACKEND_REQUEST_SERVER_INSTANCE_ID 0x5678
#define BACKEND_REQUEST_SERVER_METHOD_ID 0x0421
#define BACKEND_SERVER_CHECK_INTERNET_CONNECTION_METHOD_ID 0x0441
// #define GNSS_REQUEST_METHOD_ID 0x0421


#endif